/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BakaRouteImport } from './routes/baka'
import { Route as BakbokRouteImport } from './routes/bakbok'
import { Route as LarDigRouteImport } from './routes/lar-dig'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as BakaIndexRouteImport } from './routes/baka.index'
import { Route as BakaSlugRouteImport } from './routes/baka.$slug'
import { Route as LarDigIndexRouteImport } from './routes/lar-dig.index'
import { Route as LarDigSlugRouteImport } from './routes/lar-dig.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BakaRoute = BakaRouteImport.update({
  id: '/baka',
  path: '/baka',
  getParentRoute: () => rootRouteImport,
} as any)
const BakbokRoute = BakbokRouteImport.update({
  id: '/bakbok',
  path: '/bakbok',
  getParentRoute: () => rootRouteImport,
} as any)
const LarDigRoute = LarDigRouteImport.update({
  id: '/lar-dig',
  path: '/lar-dig',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const BakaIndexRoute = BakaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BakaRoute,
} as any)
const BakaSlugRoute = BakaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BakaRoute,
} as any)
const LarDigIndexRoute = LarDigIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LarDigRoute,
} as any)
const LarDigSlugRoute = LarDigSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LarDigRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/baka': typeof BakaRouteWithChildren
  '/bakbok': typeof BakbokRoute
  '/lar-dig': typeof LarDigRouteWithChildren
  '/profil': typeof ProfilRoute
  '/baka/$slug': typeof BakaSlugRoute
  '/lar-dig/$slug': typeof LarDigSlugRoute
  '/baka/': typeof BakaIndexRoute
  '/lar-dig/': typeof LarDigIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bakbok': typeof BakbokRoute
  '/profil': typeof ProfilRoute
  '/baka/$slug': typeof BakaSlugRoute
  '/lar-dig/$slug': typeof LarDigSlugRoute
  '/baka': typeof BakaIndexRoute
  '/lar-dig': typeof LarDigIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/baka': typeof BakaRouteWithChildren
  '/bakbok': typeof BakbokRoute
  '/lar-dig': typeof LarDigRouteWithChildren
  '/profil': typeof ProfilRoute
  '/baka/$slug': typeof BakaSlugRoute
  '/lar-dig/$slug': typeof LarDigSlugRoute
  '/baka/': typeof BakaIndexRoute
  '/lar-dig/': typeof LarDigIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/baka'
    | '/bakbok'
    | '/lar-dig'
    | '/profil'
    | '/baka/$slug'
    | '/lar-dig/$slug'
    | '/baka/'
    | '/lar-dig/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bakbok'
    | '/profil'
    | '/baka/$slug'
    | '/lar-dig/$slug'
    | '/baka'
    | '/lar-dig'
  id:
    | '__root__'
    | '/'
    | '/baka'
    | '/bakbok'
    | '/lar-dig'
    | '/profil'
    | '/baka/$slug'
    | '/lar-dig/$slug'
    | '/baka/'
    | '/lar-dig/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BakaRoute: typeof BakaRouteWithChildren
  BakbokRoute: typeof BakbokRoute
  LarDigRoute: typeof LarDigRouteWithChildren
  ProfilRoute: typeof ProfilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baka': {
      id: '/baka'
      path: '/baka'
      fullPath: '/baka'
      preLoaderRoute: typeof BakaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bakbok': {
      id: '/bakbok'
      path: '/bakbok'
      fullPath: '/bakbok'
      preLoaderRoute: typeof BakbokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lar-dig': {
      id: '/lar-dig'
      path: '/lar-dig'
      fullPath: '/lar-dig'
      preLoaderRoute: typeof LarDigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baka/': {
      id: '/baka/'
      path: '/'
      fullPath: '/baka/'
      preLoaderRoute: typeof BakaIndexRouteImport
      parentRoute: typeof BakaRoute
    }
    '/baka/$slug': {
      id: '/baka/$slug'
      path: '/$slug'
      fullPath: '/baka/$slug'
      preLoaderRoute: typeof BakaSlugRouteImport
      parentRoute: typeof BakaRoute
    }
    '/lar-dig/': {
      id: '/lar-dig/'
      path: '/'
      fullPath: '/lar-dig/'
      preLoaderRoute: typeof LarDigIndexRouteImport
      parentRoute: typeof LarDigRoute
    }
    '/lar-dig/$slug': {
      id: '/lar-dig/$slug'
      path: '/$slug'
      fullPath: '/lar-dig/$slug'
      preLoaderRoute: typeof LarDigSlugRouteImport
      parentRoute: typeof LarDigRoute
    }
  }
}

interface BakaRouteChildren {
  BakaSlugRoute: typeof BakaSlugRoute
  BakaIndexRoute: typeof BakaIndexRoute
}

const BakaRouteChildren: BakaRouteChildren = {
  BakaSlugRoute: BakaSlugRoute,
  BakaIndexRoute: BakaIndexRoute,
}

const BakaRouteWithChildren = BakaRoute._addFileChildren(BakaRouteChildren)

interface LarDigRouteChildren {
  LarDigSlugRoute: typeof LarDigSlugRoute
  LarDigIndexRoute: typeof LarDigIndexRoute
}

const LarDigRouteChildren: LarDigRouteChildren = {
  LarDigSlugRoute: LarDigSlugRoute,
  LarDigIndexRoute: LarDigIndexRoute,
}

const LarDigRouteWithChildren =
  LarDigRoute._addFileChildren(LarDigRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BakaRoute: BakaRouteWithChildren,
  BakbokRoute: BakbokRoute,
  LarDigRoute: LarDigRouteWithChildren,
  ProfilRoute: ProfilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
