/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BakaRouteImport } from './routes/baka'
import { Route as BakbokRouteImport } from './routes/bakbok'
import { Route as BakaIndexRouteImport } from './routes/baka.index'
import { Route as BakaSlugRouteImport } from './routes/baka.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BakaRoute = BakaRouteImport.update({
  id: '/baka',
  path: '/baka',
  getParentRoute: () => rootRouteImport,
} as any)
const BakbokRoute = BakbokRouteImport.update({
  id: '/bakbok',
  path: '/bakbok',
  getParentRoute: () => rootRouteImport,
} as any)
const BakaIndexRoute = BakaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BakaRoute,
} as any)
const BakaSlugRoute = BakaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BakaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/baka': typeof BakaRouteWithChildren
  '/bakbok': typeof BakbokRoute
  '/baka/$slug': typeof BakaSlugRoute
  '/baka/': typeof BakaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bakbok': typeof BakbokRoute
  '/baka/$slug': typeof BakaSlugRoute
  '/baka': typeof BakaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/baka': typeof BakaRouteWithChildren
  '/bakbok': typeof BakbokRoute
  '/baka/$slug': typeof BakaSlugRoute
  '/baka/': typeof BakaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/baka' | '/bakbok' | '/baka/$slug' | '/baka/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bakbok' | '/baka/$slug' | '/baka'
  id: '__root__' | '/' | '/baka' | '/bakbok' | '/baka/$slug' | '/baka/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BakaRoute: typeof BakaRouteWithChildren
  BakbokRoute: typeof BakbokRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baka': {
      id: '/baka'
      path: '/baka'
      fullPath: '/baka'
      preLoaderRoute: typeof BakaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bakbok': {
      id: '/bakbok'
      path: '/bakbok'
      fullPath: '/bakbok'
      preLoaderRoute: typeof BakbokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baka/': {
      id: '/baka/'
      path: '/'
      fullPath: '/baka/'
      preLoaderRoute: typeof BakaIndexRouteImport
      parentRoute: typeof BakaRoute
    }
    '/baka/$slug': {
      id: '/baka/$slug'
      path: '/$slug'
      fullPath: '/baka/$slug'
      preLoaderRoute: typeof BakaSlugRouteImport
      parentRoute: typeof BakaRoute
    }
  }
}

interface BakaRouteChildren {
  BakaSlugRoute: typeof BakaSlugRoute
  BakaIndexRoute: typeof BakaIndexRoute
}

const BakaRouteChildren: BakaRouteChildren = {
  BakaSlugRoute: BakaSlugRoute,
  BakaIndexRoute: BakaIndexRoute,
}

const BakaRouteWithChildren = BakaRoute._addFileChildren(BakaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BakaRoute: BakaRouteWithChildren,
  BakbokRoute: BakbokRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
